// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWTOJtlhQq6FTzPajT-dBRP8pjajHrCBE',
    appId: '1:394531314157:android:3a4c24b786ec9e727dafe4',
    messagingSenderId: '394531314157',
    projectId: 'unimal-project',
    storageBucket: 'unimal-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3KdBTFuKZCJfBasS9KMa1eVUtNAHBidI',
    appId: '1:394531314157:ios:4dc4a5aad6708b6e7dafe4',
    messagingSenderId: '394531314157',
    projectId: 'unimal-project',
    storageBucket: 'unimal-project.firebasestorage.app',
    androidClientId: '394531314157-6u944tq0nbsfe4clfo8r3189cta59j48.apps.googleusercontent.com',
    iosClientId: '394531314157-3ou1pqr5fofilses1e7tro8obl19hoea.apps.googleusercontent.com',
    iosBundleId: 'com.unimal.ios',
  );
}
